# Generated by Django 5.1.6 on 2025-02-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartplan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='name',
            new_name='title',
        ),
    ]
